name: Publish Proctor

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to checkout from the repo (empty uses the default branch)'
        default: ''
        required: false
        type: string

jobs:
  findNextVersion:
    name: Find Next Version Number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - run: |
          echo "plugins { id 'com.indeed.oss' version '1+' }" > build.gradle
          echo "indeedOss.activateFeature 'find-next-version'" >> build.gradle
      - uses: gradle/gradle-build-action@v2.0.1
        with:
          gradle-version: 7.3.3
          arguments: findNextVersion --group com.indeed --name proctor-common --refresh-dependencies
      - uses: actions/upload-artifact@v2
        with:
          name: version
          path: nextversion.txt
          retention-days: 1
  build:
    name: Build Project
    needs: findNextVersion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: indeedeng/proctor
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - uses: actions/download-artifact@v2
        with:
          name: version
          path: version
      - run: |
          VERSION=$(cat version/nextversion.txt)
          ./mvnw -q org.codehaus.mojo:versions-maven-plugin:2.3:set -DgenerateBackupPoms=false -DnewVersion="$VERSION"
      - run: ./mvnw "-DaltDeploymentRepository=repo::default::file://maven-publish" deploy
      - uses: actions/upload-artifact@v2
        with:
          name: publishArtifacts
          path: 'maven-publish'
          retention-days: 1
  upload:
    name: Verify and Upload
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: publishArtifacts
          path: artifacts
      - run: ./verify.sh
        env:
          REPO: proctor
          REF: ${{ github.event.inputs.ref }}
      - run: ./sign.sh
        env:
          SIGNING_SECRING_B64: ${{ secrets.SIGNING_SECRING_B64 }}
          SIGNING_KEYNAME: ${{ secrets.SIGNING_KEYNAME }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
      - run: ./upload.sh
        env:
          SONATYPE_OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          SONATYPE_OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          SONATYPE_OSSRH_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_OSSRH_STAGING_PROFILE_ID }}
